/**
 * Generates supabase/seed.sql from the existing dummy catalog (data/products.ts,
 * data/categories.ts) so the real schema starts from the exact same 47 products
 * STEP 01-07 have been built and tested against. Re-run with:
 *   npx tsx scripts/generateSeed.ts
 * whenever the dummy catalog changes, then re-check the diff of supabase/seed.sql.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { categories } from "../data/categories";
import {
  allProducts,
  bestProducts,
  discountProducts,
  domesticProducts,
  overseasProducts,
} from "../data/products";
import type { Product, ShippingType } from "../types";
import type { CountryCode } from "../types/market";

const DEFAULT_SHIPPING_FEE_KRW: Record<ShippingType, number> = {
  domestic: 3000,
  overseas_direct: 5000,
  overseas_agent: 6000,
};

const ETA_DAYS: Record<ShippingType, [number, number]> = {
  domestic: [1, 3],
  overseas_direct: [10, 25],
  overseas_agent: [10, 25],
};

const SUPPLY_TYPE: Record<ShippingType, string> = {
  domestic: "DOMESTIC_STOCK",
  overseas_direct: "OVERSEAS_DIRECT",
  overseas_agent: "OVERSEAS_AGENCY",
};

const SHIPPING_TYPE_DB: Record<ShippingType, string> = {
  domestic: "DOMESTIC",
  overseas_direct: "OVERSEAS_DIRECT",
  overseas_agent: "OVERSEAS_AGENCY",
};

const DEV_INR_RATE = 0.06; // mirrors lib/currency.ts DEV_EXCHANGE_RATES.INR — dev-only conversion, not a real rate.

const CATEGORY_NAME_EN: Record<string, string> = {
  goods: "Goods",
  baby: "Baby & Kids",
  kitchen: "Kitchen",
  living: "Household",
  interior: "Home & Interior",
  digital: "Electronics",
  car: "Car Accessories",
  hobby: "Toys & Hobby",
  stationery: "Stationery & Office",
  pet: "Pet Supplies",
};

const CATEGORY_ICON_NAME: Record<string, string> = {
  goods: "ShoppingBag",
  baby: "Baby",
  kitchen: "Utensils",
  living: "House",
  interior: "Sofa",
  digital: "MonitorSmartphone",
  car: "Car",
  hobby: "Puzzle",
  stationery: "PenLine",
  pet: "PawPrint",
};

function deterministicUuid(seed: string): string {
  const hash = createHash("sha1").update(seed).digest();
  const bytes = Buffer.from(hash.subarray(0, 16));
  bytes[6] = (bytes[6] & 0x0f) | 0x50; // version 5 marker, for reproducibility only
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return String(value);
}

function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}

function sqlJson(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

/** Reproduces the dummy-data convention ("no availableCountries" = ships everywhere) as explicit rows, since the DB model requires an explicit opt-in row per market. */
function resolveAvailableMarkets(product: Product): CountryCode[] {
  if (!product.availableCountries || product.availableCountries.length === 0) {
    return ["KR", "IN"];
  }
  return product.availableCountries;
}

function resolvePriceForMarket(product: Product, market: CountryCode): { currency: string; original: number; sale: number } {
  if (market === "KR") {
    return { currency: "KRW", original: product.originalPrice, sale: product.salePrice };
  }
  const override = product.marketPrices?.IN;
  if (override) {
    return { currency: "INR", original: override.originalPrice, sale: override.salePrice };
  }
  return {
    currency: "INR",
    original: Math.round(product.originalPrice * DEV_INR_RATE),
    sale: Math.round(product.salePrice * DEV_INR_RATE),
  };
}

function resolveShippingFee(product: Product, market: CountryCode): number {
  if (product.freeShipping) return 0;
  return product.shippingFees?.[market] ?? DEFAULT_SHIPPING_FEE_KRW[product.shippingType];
}

const lines: string[] = [
  "-- Generated by scripts/generateSeed.ts from data/products.ts + data/categories.ts — do not hand-edit.",
  "-- Run via `supabase db reset` (applies migrations, then this file) once a real project is linked.",
  "",
];

// ---- categories -------------------------------------------------------
const categoryIds = new Map<string, string>();
lines.push("-- categories");
categories.forEach((category, index) => {
  const id = deterministicUuid(`category:${category.id}`);
  categoryIds.set(category.id, id);
  lines.push(
    `insert into public.categories (id, slug, name_ko, name_en, icon_name, level, sort_order, is_visible, show_on_home) values (` +
      `'${id}', ${sqlString(category.id)}, ${sqlString(category.label)}, ${sqlString(CATEGORY_NAME_EN[category.id] ?? category.label)}, ` +
      `${sqlString(CATEGORY_ICON_NAME[category.id] ?? null)}, 1, ${index}, true, true);`
  );
});
// Spec section 4: exists in the full category list, deliberately not one of HOME's 10 quick icons.
const sportsCategoryId = deterministicUuid("category:sports");
categoryIds.set("sports", sportsCategoryId);
lines.push(
  `insert into public.categories (id, slug, name_ko, name_en, icon_name, level, sort_order, is_visible, show_on_home) values (` +
    `'${sportsCategoryId}', 'sports', '스포츠/레저', 'Sports & Leisure', 'Dumbbell', 1, ${categories.length}, true, false);`
);
lines.push("");

// ---- products + prices + shipping markets ------------------------------
const productIds = new Map<string, string>();
lines.push("-- products");
for (const product of allProducts) {
  const productId = deterministicUuid(`product:${product.id}`);
  productIds.set(product.id, productId);
  const categoryId = categoryIds.get(product.category);
  if (!categoryId) {
    throw new Error(`Product ${product.id} references unknown category ${product.category}`);
  }

  lines.push(
    `insert into public.products (` +
      `id, sku, category_id, slug, brand, name_ko, name_en, description_ko, description_en, ` +
      `origin_country, supply_type, shipping_type, default_shipping_method, stock_type, stock_quantity, ` +
      `option_groups, is_active, rating, review_count, free_shipping, discount_rate` +
      `) values (` +
      `'${productId}', ${sqlString(`SKU-${product.id.toUpperCase()}`)}, '${categoryId}', ${sqlString(product.id)}, ` +
      `${sqlString(product.brand ?? null)}, ${sqlString(product.name)}, null, ${sqlString(product.description ?? null)}, null, ` +
      `${sqlString(product.originCountry ?? null)}, '${SUPPLY_TYPE[product.shippingType]}', '${SHIPPING_TYPE_DB[product.shippingType]}', ` +
      `${product.internationalShippingMethod ? `'${product.internationalShippingMethod}'` : "null"}, ` +
      `${typeof product.stock === "number" ? "'TRACKED'" : "'UNLIMITED'"}, ${sqlNumber(product.stock ?? 0)}, ` +
      `${sqlJson(product.options ?? [])}, true, ${sqlNumber(product.rating)}, ${sqlNumber(product.reviewCount)}, ` +
      `${sqlBool(product.freeShipping)}, ${sqlNumber(product.discountRate ?? null)}` +
      `);`
  );

  const markets = resolveAvailableMarkets(product);
  for (const market of markets) {
    const price = resolvePriceForMarket(product, market);
    lines.push(
      `insert into public.product_prices (product_id, market_code, currency_code, original_price, sale_price, is_active) values (` +
        `'${productId}', '${market}', '${price.currency}', ${price.original}, ${price.sale}, true);`
    );

    const [minDays, maxDays] = ETA_DAYS[product.shippingType];
    const shippingMethod =
      product.shippingType === "overseas_direct" ? (product.internationalShippingMethod ?? "SEA") : null;
    lines.push(
      `insert into public.product_shipping_markets (` +
        `product_id, country_code, is_available, shipping_fee, estimated_min_days, estimated_max_days, shipping_method` +
        `) values (` +
        `'${productId}', '${market}', true, ${resolveShippingFee(product, market)}, ${minDays}, ${maxDays}, ` +
        `${shippingMethod ? `'${shippingMethod}'` : "null"});`
    );
  }
}

// ---- HOME section curation (STEP 08.5 item 8) --------------------------
// Reproduces data/products.ts's hand-picked arrays exactly, via the
// home_sections rows the migration already inserted (looked up by section_key
// since their ids are gen_random_uuid(), not deterministic).
lines.push("-- home section curation");
const HOME_SECTIONS: { key: string; products: Product[] }[] = [
  { key: "BEST", products: bestProducts },
  { key: "DOMESTIC_FEATURED", products: domesticProducts },
  { key: "OVERSEAS_FEATURED", products: overseasProducts },
  { key: "DISCOUNT_FEATURED", products: discountProducts },
];
for (const section of HOME_SECTIONS) {
  section.products.forEach((product, index) => {
    const productId = productIds.get(product.id);
    if (!productId) throw new Error(`Home section ${section.key} references unknown product ${product.id}`);
    lines.push(
      `insert into public.home_section_items (section_id, product_id, sort_order) ` +
        `select hs.id, '${productId}', ${index} from public.home_sections hs where hs.section_key = '${section.key}';`
    );
  });
}
lines.push("");

// ---- minimal product_images / product_variants for verification --------
// Spec item 3 (STEP 08.5): not every product needs images/options seeded —
// enough to exercise the schema: options + no-options, and all three shipping
// types. Images are self-contained inline SVG placeholders (no external
// network call, and unambiguously placeholders — not pretending to be real
// product photography, since none exists in this project).
const VERIFICATION_PRODUCT_IDS = ["best-1", "best-3", "overseas-1", "overseas-2", "overseas-6", "domestic-1"];

function placeholderImageDataUri(label: string, bgHex: string): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600">` +
    `<rect width="600" height="600" fill="#${bgHex}"/>` +
    `<text x="50%" y="50%" font-size="28" fill="#ffffff" text-anchor="middle" dominant-baseline="middle" font-family="sans-serif">${label}</text>` +
    `</svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;
}

function cartesian(groups: { name: string; choices: string[] }[]): Record<string, string>[] {
  return groups.reduce<Record<string, string>[]>(
    (acc, group) => acc.flatMap((combo) => group.choices.map((choice) => ({ ...combo, [group.name]: choice }))),
    [{}]
  );
}

lines.push("-- product_images / product_variants (verification subset only)");
for (const productSlug of VERIFICATION_PRODUCT_IDS) {
  const product = allProducts.find((item) => item.id === productSlug);
  const productId = productIds.get(productSlug);
  if (!product || !productId) throw new Error(`Verification product ${productSlug} not found`);

  const primaryImage = placeholderImageDataUri(product.name.slice(0, 12), "098774");
  lines.push(
    `insert into public.product_images (product_id, image_url, alt_ko, sort_order, is_primary) values (` +
      `'${productId}', ${sqlString(primaryImage)}, ${sqlString(product.name)}, 0, true);`
  );
  const secondaryImage = placeholderImageDataUri(`${product.name.slice(0, 10)} 2`, "07695b");
  lines.push(
    `insert into public.product_images (product_id, image_url, alt_ko, sort_order, is_primary) values (` +
      `'${productId}', ${sqlString(secondaryImage)}, ${sqlString(product.name)}, 1, false);`
  );

  if (product.options && product.options.length > 0) {
    const combos = cartesian(product.options);
    const perVariantStock = Math.max(1, Math.floor((product.stock ?? 20) / combos.length));
    combos.forEach((combo, index) => {
      const variantSku = `SKU-${productSlug.toUpperCase()}-V${index + 1}`;
      lines.push(
        `insert into public.product_variants (product_id, sku, option_values, additional_price, stock_quantity, is_active) values (` +
          `'${productId}', ${sqlString(variantSku)}, ${sqlJson(combo)}, 0, ${perVariantStock}, true);`
      );
    });
  }
}

const outPath = path.join(__dirname, "..", "supabase", "seed.sql");
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${outPath} (${allProducts.length} products, ${categories.length + 1} categories)`);
